groups:
  - name: metis-seq
    interval: 15s
    rules:
      - alert: ChainStalled
        expr: increase(metis:sequencer:height[1m]) == 0
        labels:
          severity: high
        annotations:
          summary: "{{ $labels.svc_name }} of {{ $labels.seq_name }} is has no new blocks in the past minute"
      - alert: ScrapeFailures
        expr: increase(metis_sequencer_exporter_failures[1m]) > 2
        for: 3m
        labels:
          severity: high
        annotations:
          summary: "Failed to scrape metrics from {{ $labels.url }}, see the exporter log to fix it"
